const citiesData = {
    // North America
    "New York": {
        temp: 20,
        feelsLike: 18,
        humidity: 65,
        description: "partly cloudy",
        icon: "02d",
        wind: { speed: 12, direction: "NE" },
        pressure: 1015,
        visibility: 10,
        uvIndex: 5,
        precipitation: 20
    },
    "Los Angeles": {
        temp: 25,
        feelsLike: 26,
        humidity: 60,
        description: "clear sky",
        icon: "01d",
        wind: { speed: 8, direction: "W" },
        pressure: 1012,
        visibility: 16,
        uvIndex: 8,
        precipitation: 0
    },
    "Chicago": {
        temp: 15,
        feelsLike: 13,
        humidity: 70,
        description: "scattered clouds",
        icon: "03d",
        wind: { speed: 15, direction: "NW" },
        pressure: 1008,
        visibility: 12,
        uvIndex: 4,
        precipitation: 30
    },
    "Toronto": {
        temp: 12,
        feelsLike: 10,
        humidity: 68,
        description: "light rain",
        icon: "10d",
        wind: { speed: 14, direction: "N" },
        pressure: 1010,
        visibility: 8,
        uvIndex: 3,
        precipitation: 60
    },
    "Mexico City": {
        temp: 23,
        feelsLike: 24,
        humidity: 55,
        description: "mostly sunny",
        icon: "02d",
        wind: { speed: 10, direction: "SE" },
        pressure: 1023,
        visibility: 15,
        uvIndex: 9,
        precipitation: 10
    },
    "Vancouver": {
        temp: 15,
        feelsLike: 14,
        humidity: 73,
        description: "overcast clouds",
        icon: "04d",
        wind: { speed: 11, direction: "SW" },
        pressure: 1013,
        visibility: 14,
        uvIndex: 2,
        precipitation: 40
    },
    "Miami": {
        temp: 29,
        feelsLike: 32,
        humidity: 75,
        description: "thunderstorm",
        icon: "11d",
        wind: { speed: 18, direction: "SE" },
        pressure: 1005,
        visibility: 6,
        uvIndex: 7,
        precipitation: 80
    },
    "Montreal": {
        temp: 10,
        feelsLike: 8,
        humidity: 65,
        description: "light snow",
        icon: "13d",
        wind: { speed: 16, direction: "NW" },
        pressure: 1018,
        visibility: 10,
        uvIndex: 2,
        precipitation: 50
    },

    // Europe
    "London": {
        temp: 15,
        feelsLike: 13,
        humidity: 75,
        description: "light rain",
        icon: "10d",
        wind: { speed: 15, direction: "SW" },
        pressure: 1011,
        visibility: 9,
        uvIndex: 3,
        precipitation: 70
    },
    "Paris": {
        temp: 18,
        feelsLike: 17,
        humidity: 70,
        description: "scattered clouds",
        icon: "03d",
        wind: { speed: 10, direction: "W" },
        pressure: 1014,
        visibility: 12,
        uvIndex: 4,
        precipitation: 25
    },
    "Berlin": {
        temp: 16,
        feelsLike: 15,
        humidity: 72,
        description: "overcast clouds",
        icon: "04d",
        wind: { speed: 11, direction: "NW" },
        pressure: 1012,
        visibility: 11,
        uvIndex: 3,
        precipitation: 35
    },
    "Rome": {
        temp: 22,
        feelsLike: 23,
        humidity: 65,
        description: "clear sky",
        icon: "01d",
        wind: { speed: 9, direction: "S" },
        pressure: 1015,
        visibility: 15,
        uvIndex: 7,
        precipitation: 5
    },
    "Madrid": {
        temp: 24,
        feelsLike: 25,
        humidity: 50,
        description: "sunny",
        icon: "01d",
        wind: { speed: 13, direction: "NE" },
        pressure: 1016,
        visibility: 16,
        uvIndex: 8,
        precipitation: 0
    },
    "Amsterdam": {
        temp: 14,
        feelsLike: 12,
        humidity: 78,
        description: "light rain",
        icon: "10d",
        wind: { speed: 17, direction: "W" },
        pressure: 1009,
        visibility: 8,
        uvIndex: 2,
        precipitation: 65
    },
    "Moscow": {
        temp: 5,
        feelsLike: 2,
        humidity: 80,
        description: "snow",
        icon: "13d",
        wind: { speed: 18, direction: "N" },
        pressure: 1020,
        visibility: 5,
        uvIndex: 1,
        precipitation: 85
    },
    "Stockholm": {
        temp: 10,
        feelsLike: 8,
        humidity: 75,
        description: "light snow",
        icon: "13d",
        wind: { speed: 13, direction: "NE" },
        pressure: 1017,
        visibility: 7,
        uvIndex: 2,
        precipitation: 45
    },

    // Asia
    "Tokyo": {
        temp: 25,
        feelsLike: 26,
        humidity: 60,
        description: "clear sky",
        icon: "01d",
        wind: { speed: 8, direction: "SE" },
        pressure: 1013,
        visibility: 14,
        uvIndex: 6,
        precipitation: 10
    },
    "Beijing": {
        temp: 19,
        feelsLike: 18,
        humidity: 58,
        description: "haze",
        icon: "50d",
        wind: { speed: 10, direction: "N" },
        pressure: 1016,
        visibility: 4,
        uvIndex: 3,
        precipitation: 15
    },
    "Shanghai": {
        temp: 26,
        feelsLike: 28,
        humidity: 70,
        description: "cloudy",
        icon: "03d",
        wind: { speed: 12, direction: "E" },
        pressure: 1010,
        visibility: 8,
        uvIndex: 5,
        precipitation: 30
    },
    "Hong Kong": {
        temp: 28,
        feelsLike: 31,
        humidity: 75,
        description: "scattered thunderstorms",
        icon: "11d",
        wind: { speed: 15, direction: "SE" },
        pressure: 1008,
        visibility: 7,
        uvIndex: 6,
        precipitation: 70
    },
    "Singapore": {
        temp: 30,
        feelsLike: 34,
        humidity: 75,
        description: "thunderstorm",
        icon: "11d",
        wind: { speed: 8, direction: "SW" },
        pressure: 1009,
        visibility: 9,
        uvIndex: 8,
        precipitation: 75
    },
    "Seoul": {
        temp: 20,
        feelsLike: 19,
        humidity: 62,
        description: "scattered clouds",
        icon: "03d",
        wind: { speed: 11, direction: "W" },
        pressure: 1014,
        visibility: 13,
        uvIndex: 5,
        precipitation: 20
    },
    "Mumbai": {
        temp: 32,
        feelsLike: 36,
        humidity: 70,
        description: "haze",
        icon: "50d",
        wind: { speed: 9, direction: "SW" },
        pressure: 1008,
        visibility: 5,
        uvIndex: 9,
        precipitation: 25
    },
    "Bangkok": {
        temp: 33,
        feelsLike: 37,
        humidity: 65,
        description: "scattered clouds",
        icon: "03d",
        wind: { speed: 10, direction: "S" },
        pressure: 1010,
        visibility: 12,
        uvIndex: 10,
        precipitation: 30
    },

    // Australia and Oceania
    "Sydney": {
        temp: 28,
        feelsLike: 29,
        humidity: 55,
        description: "sunny",
        icon: "01d",
        wind: { speed: 14, direction: "NE" },
        pressure: 1015,
        visibility: 16,
        uvIndex: 9,
        precipitation: 5
    },
    "Melbourne": {
        temp: 25,
        feelsLike: 24,
        humidity: 60,
        description: "partly cloudy",
        icon: "02d",
        wind: { speed: 16, direction: "S" },
        pressure: 1012,
        visibility: 15,
        uvIndex: 7,
        precipitation: 15
    },
    "Brisbane": {
        temp: 27,
        feelsLike: 28,
        humidity: 65,
        description: "scattered clouds",
        icon: "03d",
        wind: { speed: 12, direction: "E" },
        pressure: 1014,
        visibility: 14,
        uvIndex: 8,
        precipitation: 20
    },
    "Auckland": {
        temp: 22,
        feelsLike: 21,
        humidity: 70,
        description: "light rain",
        icon: "10d",
        wind: { speed: 15, direction: "SW" },
        pressure: 1011,
        visibility: 11,
        uvIndex: 6,
        precipitation: 45
    },

    // Middle East
    "Dubai": {
        temp: 35,
        feelsLike: 39,
        humidity: 45,
        description: "clear sky",
        icon: "01d",
        wind: { speed: 16, direction: "NW" },
        pressure: 1008,
        visibility: 15,
        uvIndex: 11,
        precipitation: 0
    },
    "Abu Dhabi": {
        temp: 34,
        feelsLike: 38,
        humidity: 48,
        description: "clear sky",
        icon: "01d",
        wind: { speed: 14, direction: "NW" },
        pressure: 1009,
        visibility: 14,
        uvIndex: 10,
        precipitation: 0
    },
    "Doha": {
        temp: 33,
        feelsLike: 37,
        humidity: 50,
        description: "sunny",
        icon: "01d",
        wind: { speed: 13, direction: "N" },
        pressure: 1010,
        visibility: 15,
        uvIndex: 10,
        precipitation: 0
    },
    "Istanbul": {
        temp: 21,
        feelsLike: 20,
        humidity: 63,
        description: "partly cloudy",
        icon: "02d",
        wind: { speed: 12, direction: "NE" },
        pressure: 1013,
        visibility: 13,
        uvIndex: 6,
        precipitation: 15
    },

    // Africa
    "Cairo": {
        temp: 29,
        feelsLike: 31,
        humidity: 40,
        description: "clear sky",
        icon: "01d",
        wind: { speed: 15, direction: "N" },
        pressure: 1012,
        visibility: 14,
        uvIndex: 9,
        precipitation: 0
    },
    "Lagos": {
        temp: 31,
        feelsLike: 35,
        humidity: 75,
        description: "scattered thunderstorms",
        icon: "11d",
        wind: { speed: 11, direction: "SW" },
        pressure: 1010,
        visibility: 8,
        uvIndex: 8,
        precipitation: 65
    },
    "Nairobi": {
        temp: 25,
        feelsLike: 26,
        humidity: 65,
        description: "partly cloudy",
        icon: "02d",
        wind: { speed: 12, direction: "E" },
        pressure: 1015,
        visibility: 12,
        uvIndex: 9,
        precipitation: 25
    },
    "Cape Town": {
        temp: 23,
        feelsLike: 22,
        humidity: 65,
        description: "partly cloudy",
        icon: "02d",
        wind: { speed: 16, direction: "SE" },
        pressure: 1014,
        visibility: 15,
        uvIndex: 8,
        precipitation: 10
    },

    // South America
    "Rio de Janeiro": {
        temp: 27,
        feelsLike: 29,
        humidity: 72,
        description: "scattered clouds",
        icon: "03d",
        wind: { speed: 12, direction: "SE" },
        pressure: 1011,
        visibility: 13,
        uvIndex: 9,
        precipitation: 35
    },
    "São Paulo": {
        temp: 25,
        feelsLike: 26,
        humidity: 68,
        description: "light rain",
        icon: "10d",
        wind: { speed: 10, direction: "E" },
        pressure: 1012,
        visibility: 12,
        uvIndex: 7,
        precipitation: 45
    },
    "Buenos Aires": {
        temp: 24,
        feelsLike: 25,
        humidity: 65,
        description: "mostly sunny",
        icon: "02d",
        wind: { speed: 14, direction: "E" },
        pressure: 1013,
        visibility: 14,
        uvIndex: 8,
        precipitation: 15
    },
    "Lima": {
        temp: 22,
        feelsLike: 23,
        humidity: 75,
        description: "cloudy",
        icon: "04d",
        wind: { speed: 11, direction: "S" },
        pressure: 1014,
        visibility: 10,
        uvIndex: 6,
        precipitation: 20
    }
};
